# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170629_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips_on',
            name='type',
        ),
    ]
