# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20170629_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='date',
        ),
        migrations.AddField(
            model_name='tips',
            name='title',
            field=models.CharField(default='title', max_length=16),
        ),
    ]
